name: Backend CI Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - feature


jobs:
  unit-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup NodeJS Version
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - name: Install Dependencies
        working-directory: backend
        run: npm install

      - name: Unit Testing
        working-directory: backend
        run: npm test
        continue-on-error: true

      - name: Archive Test Result
        uses: actions/upload-artifact@v4
        with:
          name: Backend-Test-Result
          path: backend/test-results.xml

  code-coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    needs: unit-testing
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        working-directory: backend
        run: npm install

      - name: Check Code Coverage
        working-directory: backend
        run: npm run coverage
        continue-on-error: true

      - name: Archive Coverage Result
        uses: actions/upload-artifact@v4
        with:
          name: Backend-Code-Coverage
          path: backend/coverage
          retention-days: 5

  docker:
    name: Backend Containerization
    runs-on: ubuntu-latest
    needs: [unit-testing, code-coverage]
    steps:
      - uses: actions/checkout@v4

      - name: DockerHub Login
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Debug Backend Directory
        run: ls -la backend

      - name: Docker Build (Backend)
        uses: docker/build-push-action@v6
        with:
          context: ./backend          # ✅ backend context
          file: ./backend/Dockerfile  # ✅ explicit Dockerfile
          push: false
          tags: |
            bhargavdanda123/backend-app:${{ github.sha }}

      - name: Docker Push
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            bhargavdanda123/backend-app:${{ github.sha }}
            bhargavdanda123/backend-app:latest
